if(process.platform==='android')Object.defineProperty(process,'platform',{value:'linux'});
const fs=require('node:fs'),http=require('node:http'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require('../../folio/node_modules/playwright');
const launch=require('../../folio/tests/gpu-launch.cjs');
const root=path.resolve(__dirname,'../assets');
const server=http.createServer((req,res)=>{const name=decodeURIComponent(req.url.split('?')[0]);const file=path.join(root,name==='/'?'index.html':name);if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(err,data)=>{if(err){res.writeHead(404).end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.html')?'text/html':file.endsWith('.ttf')?'font/ttf':file.endsWith('.woff2')?'font/woff2':'text/plain');res.end(data);});});
(async()=>{
 await new Promise(r=>server.listen(8789,'127.0.0.1',r));
 const browser=await chromium.launch({...launch(),headless:true});
 const context=await browser.newContext({viewport:{width:412,height:915},deviceScaleFactor:1,hasTouch:true});
 const page=await context.newPage();const errors=[];const externalRequests=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:8789/'))externalRequests.push(r.url());});
 try{
  await page.goto('http://127.0.0.1:8789/');await page.waitForFunction(()=>!!window.Nightwire);
  await page.getByRole('heading',{name:'Reading desk'}).waitFor();
  await page.screenshot({path:path.resolve(__dirname,'home-phone.png'),fullPage:true});
  await page.getByRole('button',{name:'Explore a sample'}).click();
  await page.waitForFunction(()=>document.querySelector('#nav-count')?.textContent==='3');
  await page.locator('.reader-toolbar').waitFor();await page.waitForFunction(()=>document.querySelector('#markdown')?.textContent.includes('Reading systems'));
  await page.getByRole('button',{name:'Home',exact:true}).click();await page.waitForTimeout(650);await page.screenshot({path:path.resolve(__dirname,'deck-phone.png'),fullPage:true});
  await page.getByRole('button',{name:'Search',exact:true}).click();await page.getByRole('textbox',{name:'Search all files'}).fill('protocol');await page.locator('.search-result').first().waitFor();
  assert((await page.locator('.search-result').count())>0);
  await page.screenshot({path:path.resolve(__dirname,'search-phone.png'),fullPage:true});
  await page.getByRole('textbox',{name:'Search all files'}).fill('curiosit');await page.waitForFunction(()=>document.querySelector('#search-meta')?.textContent.startsWith('1 MATCH')&&document.querySelector('.search-result strong')?.textContent==='Field notes');
  await page.getByRole('textbox',{name:'Search all files'}).fill('#reading');await page.waitForFunction(()=>document.querySelector('#search-meta')?.textContent.startsWith('2 MATCH'));
  await page.getByRole('textbox',{name:'Search all files'}).fill('protocol');await page.waitForFunction(()=>[...document.querySelectorAll('.search-result strong')].some(el=>el.textContent==='Signal protocol'));
  await page.locator('.search-result').filter({has:page.getByText('Signal protocol',{exact:true})}).first().click();await page.waitForFunction(()=>document.querySelector('#markdown')?.textContent.includes('Connect deliberately'));
  await page.getByRole('button',{name:'Close find'}).click();
  await page.getByRole('button',{name:'Document outline'}).click();await page.getByRole('button',{name:/Connect deliberately/}).click();
  await page.getByRole('button',{name:'View Markdown source'}).click();assert(await page.locator('.source-view').count());assert((await page.locator('.source-view').textContent()).includes('[[Field notes]]'));
  await page.getByRole('button',{name:'Read formatted Markdown'}).click();
  await page.getByRole('button',{name:'More document tools'}).click();await page.getByRole('button',{name:'Bookmark this file',exact:true}).click();await page.getByRole('button',{name:'Close panel'}).click();
  await page.getByRole('button',{name:'Graph of this file'}).click();await page.locator('#graph-canvas canvas').waitFor();await page.getByRole('button',{name:'All files',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#graph-count')?.textContent.includes('CONNECTIONS'));
  await page.waitForTimeout(2200);await page.screenshot({path:path.resolve(__dirname,'graph-phone.png'),fullPage:true});
  assert((await page.locator('#graph-count').textContent()).match(/\d+ NODES/));
  const point=await page.locator('#graph-canvas canvas').first().evaluate(canvas=>{const ctx=canvas.getContext('2d');const p=ctx.getImageData(0,0,canvas.width,canvas.height);for(let y=0;y<canvas.height;y++)for(let x=0;x<canvas.width;x++){const i=(y*canvas.width+x)*4;if(p.data[i]===200&&p.data[i+1]===250&&p.data[i+2]===114)return {x:x/(canvas.width/canvas.clientWidth),y:y/(canvas.height/canvas.clientHeight)};}return null;});
  assert(point,'Graph must paint visible document nodes');await page.locator('#graph-canvas canvas').first().click({position:point});await page.getByRole('button',{name:'Read file',exact:true}).waitFor();await page.getByRole('button',{name:'Read file',exact:true}).click();await page.locator('#markdown h1').waitFor();
  // Direct file import through the browser fallback, preserving the native workflow's semantics.
  const hostile='# Imported safely\n\n<script>window.__pwned=1</script>\n<img src="https://example.invalid/pixel" onerror="window.__pwned=2">\n<div data-action="confirm-remove">Click me</div>\n\n## Duplicate\n\n## Duplicate\n\n- [x] Done\n\n> [!TIP]\n> A useful tip\n\n| A | B |\n| - | - |\n| a | b |\n\n```js\nconst x = 1;\n```\n\nFind the unicorn here.\n';
  await page.locator('#file-input').setInputFiles({name:'Imported safely.md',mimeType:'text/markdown',buffer:Buffer.from(hostile)});
  await page.waitForFunction(()=>document.querySelector('#markdown h1')?.textContent==='Imported safely');
  assert.equal(await page.evaluate(()=>window.__pwned),undefined);
  assert.equal(await page.locator('#markdown script,#markdown [onerror],#markdown [data-action="confirm-remove"]').count(),0);
  assert.equal(await page.locator('#markdown .table-wrap').count(),1);assert.equal(await page.locator('#markdown .callout').count(),1);assert.equal(await page.locator('#markdown .task-check').count(),1);
  assert.equal(await page.locator('#markdown h2').nth(1).getAttribute('id'),'duplicate-1');
  await page.getByRole('button',{name:'Find in this document'}).click();await page.getByRole('textbox',{name:'Find in document'}).fill('unicorn');await page.waitForFunction(()=>document.querySelector('#find-count')?.textContent==='1 / 1');
  await page.getByRole('button',{name:'Close find'}).click();await page.screenshot({path:path.resolve(__dirname,'reader-phone.png'),fullPage:true});
  const input=await page.evaluate(()=>Nightwire.classifierInput());assert.equal(input.name,'Imported safely.md');assert(input.contentRevision.length===64);assert(input.headings.length===3);
  await page.getByRole('button',{name:'More document tools'}).click();const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export analysis JSON'}).click();const download=await downloadPromise;const payload=JSON.parse(fs.readFileSync(await download.path(),'utf8'));assert.equal(payload.documentId,input.documentId);assert.equal(payload.text,input.text);assert.equal(payload.contentRevision,require('node:crypto').createHash('sha256').update(input.text).digest('hex'));
  await page.getByRole('button',{name:'Enter focus mode'}).click();assert.equal(await page.locator('.mobile-nav').isVisible(),false);await page.getByRole('button',{name:'Leave focus mode'}).click();
  await page.getByRole('button',{name:'Reading preferences',exact:true}).click();await page.getByRole('button',{name:'Increase text size'}).click();await page.getByRole('combobox',{name:'Reading typeface'}).selectOption('serif');await page.getByRole('button',{name:'Close panel'}).click();
  assert.equal(await page.evaluate(()=>getComputedStyle(document.documentElement).getPropertyValue('--font-size')),'18px');
  await page.reload();await page.waitForFunction(()=>window.Nightwire&&document.querySelector('#nav-count')?.textContent==='4');assert.equal(await page.evaluate(()=>getComputedStyle(document.documentElement).getPropertyValue('--font-size')),'18px');
  await page.getByRole('button',{name:'Continue reading'}).click();await page.locator('#markdown h1').waitFor();await page.getByRole('button',{name:'More document tools'}).click();await page.getByRole('button',{name:'Remove from recent files'}).click();await page.getByRole('button',{name:'Remove copy',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#nav-count')?.textContent==='3');
  // Palette selection changes every accent role and remains readable on black.
  await page.getByRole('button',{name:'Reading preferences',exact:true}).click();
  const palettes=[['Signal lime','neon','#c8fa72'],['Glacier','glacier','#76e5ff'],['Ultraviolet','violet','#bc9cff'],['Hot pink','pink','#ff9bcf'],['Amber terminal','amber','#ffd279'],['Ember','ember','#ffad8b'],['Mint circuit','mint','#81efc2'],['Quiet night','muted','#b5c7c0']];
  for(const [name,id,hex]of palettes){await page.getByRole('button',{name:name+' palette',exact:true}).click();assert.equal(await page.evaluate(()=>document.documentElement.dataset.palette),id);assert.equal(await page.evaluate(()=>getComputedStyle(document.documentElement).getPropertyValue('--accent')),hex);assert.equal(await page.locator('[data-palette][aria-pressed="true"]').count(),1);assert.equal(await page.locator('#palette-name').textContent(),name);const contrast=await page.evaluate(()=>{const c=getComputedStyle(document.documentElement).getPropertyValue('--accent').trim().match(/[a-f0-9]{2}/gi).map(x=>parseInt(x,16)/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4);return (c.reduce((n,v,i)=>n+v*[.2126,.7152,.0722][i],0)+.05)/.05;});assert(contrast>=4.5, name+' accent must be readable');}
  await page.getByRole('button',{name:'Ultraviolet palette',exact:true}).click();
  await page.getByRole('button',{name:'Vivid',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Vivid',exact:true}).getAttribute('aria-pressed'),'true');assert.equal(await page.getByRole('button',{name:'Balanced',exact:true}).getAttribute('aria-pressed'),'false');await page.locator('#panel-content').evaluate(el=>el.scrollTop=0);await page.waitForTimeout(180);await page.screenshot({path:path.resolve(__dirname,'palettes-phone.png')});
  const swatch=page.getByRole('button',{name:'Glacier palette',exact:true});await swatch.scrollIntoViewIfNeeded();const box=await swatch.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();assert(await swatch.evaluate(el=>el.classList.contains('is-pressed')));assert.notEqual(await swatch.evaluate(el=>getComputedStyle(el).transform),'none');await page.mouse.up();assert.equal(await swatch.evaluate(el=>el.classList.contains('is-pressed')),false);
  await page.getByRole('textbox',{name:'Custom accent hex colour'}).fill('#91B7FF');await page.getByRole('textbox',{name:'Custom accent hex colour'}).press('Enter');assert.equal(await page.evaluate(()=>document.documentElement.dataset.palette),'custom');assert.equal(await page.evaluate(()=>getComputedStyle(document.documentElement).getPropertyValue('--accent')),'#91B7FF');
  await page.getByRole('textbox',{name:'Custom accent hex colour'}).fill('#ZZZZZZ');await page.getByRole('textbox',{name:'Custom accent hex colour'}).press('Enter');assert.equal(await page.getByRole('textbox',{name:'Custom accent hex colour'}).getAttribute('aria-invalid'),'true');assert.equal(await page.evaluate(()=>getComputedStyle(document.documentElement).getPropertyValue('--accent')),'#91B7FF');
  await page.getByRole('textbox',{name:'Custom accent hex colour'}).fill('#000000');await page.getByRole('textbox',{name:'Custom accent hex colour'}).press('Enter');assert.notEqual(await page.evaluate(()=>getComputedStyle(document.documentElement).getPropertyValue('--accent')),'#000000');
  await page.getByRole('slider',{name:'Custom accent hue'}).focus();await page.getByRole('slider',{name:'Custom accent hue'}).press('End');await page.getByRole('slider',{name:'Custom accent hue'}).press('ArrowLeft');const custom=await page.evaluate(()=>JSON.parse(localStorage.getItem('settings')).customColor);assert(/^#[a-f0-9]{6}$/i.test(custom));
  await page.getByRole('switch',{name:'Motion',exact:true}).click();await page.getByRole('button',{name:'Mint circuit palette',exact:true}).click();assert.equal(await page.locator('.no-motion').count(),1);assert.equal(await page.evaluate(()=>getComputedStyle(document.body).getPropertyValue('--t-press').trim()),'0ms');const still=page.getByRole('button',{name:'Glacier palette',exact:true});await still.scrollIntoViewIfNeeded();const sb=await still.boundingBox();await page.mouse.move(sb.x+sb.width/2,sb.y+sb.height/2);await page.mouse.down();assert(await still.evaluate(el=>el.classList.contains('is-pressed')));assert.equal(await still.evaluate(el=>getComputedStyle(el).transitionDuration.split(',').every(d=>parseFloat(d)===0)),true);await page.mouse.up();assert.equal(await page.locator('.press-wave').count(),0);await page.getByRole('switch',{name:'Motion',exact:true}).click();
  await page.getByRole('button',{name:'Custom accent palette',exact:true}).click();await page.getByRole('button',{name:'Close panel'}).click();assert.equal(await page.evaluate(()=>getComputedStyle(document.body).backgroundColor),'rgb(0, 0, 0)');
  await page.reload();await page.waitForFunction(()=>window.Nightwire&&document.querySelector('#nav-count')?.textContent==='3');assert.equal(await page.evaluate(()=>document.documentElement.dataset.palette),'custom');assert.equal(await page.evaluate(()=>document.documentElement.dataset.intensity),'vivid');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('settings')).customColor),custom);
  // Recolour a settled graph without rebuilding it or leaving the settings dialog.
  await page.getByRole('button',{name:'Graph',exact:true}).click();await page.locator('#graph-canvas canvas').waitFor();await page.waitForTimeout(1400);await page.getByRole('button',{name:'Reading preferences',exact:true}).click();await page.getByRole('button',{name:'Amber terminal palette',exact:true}).click();await page.getByRole('button',{name:'Close panel'}).click();await page.waitForFunction(()=>{const canvas=document.querySelector('#graph-canvas canvas'),ctx=canvas.getContext('2d'),data=ctx.getImageData(0,0,canvas.width,canvas.height).data;for(let i=0;i<data.length;i+=4)if(data[i]===255&&data[i+1]===210&&data[i+2]===121)return true;return false;});assert.equal(await page.locator('.graph-legend b').first().evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(255, 210, 121)');
  await page.getByRole('button',{name:'Home',exact:true}).click();await page.waitForTimeout(180);await page.screenshot({path:path.resolve(__dirname,'amber-phone.png'),fullPage:true});
  for(const width of [320,412,800,1280]){await page.setViewportSize({width,height:900});await page.locator('[data-action="home"]').first().evaluate(el=>el.click());await page.waitForTimeout(150);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Layout overflows at ${width}px`);await page.screenshot({path:path.resolve(__dirname,`home-${width}.png`),fullPage:true});await page.locator('.top-actions [data-action="settings"]').click();assert(await page.locator('#panel-content').evaluate(el=>el.scrollWidth<=el.clientWidth),`Appearance panel overflows at ${width}px`);assert(await page.locator('.palette-grid').evaluate(el=>el.scrollWidth<=el.clientWidth),`Palette grid overflows at ${width}px`);if(width===320||width===1280){await page.locator('#panel-content').evaluate(el=>el.scrollTop=0);await page.waitForTimeout(180);await page.screenshot({path:path.resolve(__dirname,`palettes-${width}.png`)});}await page.getByRole('button',{name:'Close panel'}).click();}
  // Exercise the native-mode event/bridge path in a separate WebView-like context.
  const nativeContext=await browser.newContext({viewport:{width:412,height:915}});
  await nativeContext.addInitScript(()=>{const doc={id:'f'.repeat(64),name:'Hot-open.md',bytes:100,imported:Date.now(),url:'/hot-open-fixture.md'};const emit=()=>window.dispatchEvent(new CustomEvent('native-library',{detail:{docs:[doc],active:doc.id}}));window.Native={haptic(confirm){(window.__haptics||=[]).push(confirm);},list(){setTimeout(emit,100);},openFiles(){window.__picker=true;},exportStructured(name,json){window.__nativeExport={name,input:JSON.parse(json)};},copy(text){window.__copied=text;}};});
  const nativePage=await nativeContext.newPage();nativePage.on('pageerror',e=>errors.push(e.message));await nativePage.route('**/hot-open-fixture.md',r=>r.fulfill({contentType:'text/plain',body:'# Hot-open\n\nA downloaded Markdown file.\n\n## Detail\n\nNative bridge fixture.'}));
  await nativePage.goto('http://127.0.0.1:8789/');await nativePage.waitForFunction(()=>document.querySelector('#markdown h1')?.textContent==='Hot-open');await nativePage.getByRole('button',{name:'More document tools'}).click();await nativePage.getByRole('button',{name:'Export analysis JSON'}).click();await nativePage.waitForFunction(()=>!!window.__nativeExport);assert.equal((await nativePage.evaluate(()=>window.__nativeExport.input)).name,'Hot-open.md');await nativePage.getByRole('button',{name:'Open Markdown files',exact:true}).click();assert(await nativePage.evaluate(()=>window.__picker));await nativePage.getByRole('button',{name:'Reading preferences',exact:true}).click();assert((await nativePage.evaluate(()=>window.__haptics||[])).length>0);await nativePage.getByRole('switch',{name:'Touch feedback',exact:true}).click();const clicks=await nativePage.evaluate(()=>window.__haptics.length);await nativePage.getByRole('button',{name:'Hot pink palette',exact:true}).click();assert.equal(await nativePage.evaluate(()=>window.__haptics.length),clicks);await nativePage.getByRole('switch',{name:'Touch feedback',exact:true}).click();assert((await nativePage.evaluate(()=>window.__haptics.length))>clicks);await nativeContext.close();
  assert.deepEqual(errors,[]);assert.deepEqual(externalRequests,[]);
  console.log('PASS: eight palettes/custom colour, contrast, intensity, persistence, pressed travel, reduced motion, native haptics toggle, live graph recolouring, imports, sanitized rendering, search, outline, source, bookmarks, graph, find, classifier input, focus, preferences, persistence, removal, responsive layouts; no external requests.');
 }finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
