if(process.platform==='android')Object.defineProperty(process,'platform',{value:'linux'});
const fs=require('node:fs'),http=require('node:http'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require('../../folio/node_modules/playwright'),launch=require('../../folio/tests/gpu-launch.cjs');const root=path.resolve(__dirname,'../assets');
const server=http.createServer((req,res)=>{const file=path.join(root,req.url==='/'?'index.html':decodeURIComponent(req.url.split('?')[0]));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(err,data)=>{if(err){res.writeHead(404).end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.html')?'text/html':file.endsWith('.ttf')?'font/ttf':file.endsWith('.woff2')?'font/woff2':'text/plain');res.end(data);});});
(async()=>{
 await new Promise(r=>server.listen(8800,'127.0.0.1',r));const browser=await chromium.launch({...launch(),headless:true}),page=await browser.newPage({viewport:{width:412,height:915},hasTouch:true}),errors=[],external=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:8800/'))external.push(r.url());});
 const close=()=>page.getByRole('button',{name:'Close panel'}).click(),open=()=>page.getByRole('button',{name:'Choose reading typeface',exact:true}).click();
 const choose=async id=>{await page.locator('.font-option[data-font="'+id+'"]').click();await page.evaluate(()=>document.fonts.ready);assert.equal(await page.evaluate(()=>document.documentElement.dataset.readingFont),id);assert.equal(await page.locator('.font-option[aria-pressed=true]').count(),1);};
 try{
  await page.addInitScript(()=>{if(!localStorage.getItem('settings'))localStorage.setItem('settings',JSON.stringify({motion:false}));});await page.goto('http://127.0.0.1:8800/');await page.waitForFunction(()=>!!window.Nightwire);
  await page.locator('#file-input').setInputFiles({name:'A-type-specimen.md',mimeType:'text/markdown',buffer:Buffer.from('# A type specimen\n\n## Filed notes\n\n'+('Keep a small clear record of the useful words. '.repeat(45))+'\n\n```js\nconst source = true;\n```')});await page.locator('#markdown h1').waitFor();const original=await page.evaluate(()=>Nightwire.classifierInput()),codeFont=await page.locator('#markdown pre code').evaluate(el=>getComputedStyle(el).fontFamily);
  await open();assert.equal(await page.locator('.font-option').count(),20);assert.equal(await page.locator('.font-option .font-option-l').count(),3,'Legibility faces carry a stamped L');assert.equal(await page.locator('.rack-proof-line').textContent(),'Keep a small clear record of the useful words.','Proof strip shows the document\'s first sentence');
  for(const [group,count]of [['sans',9],['serif',7],['mono',4],['accessible',3],['all',20]]){await page.locator('[data-font-group="'+group+'"]').click();assert.equal(await page.locator('.font-option:visible').count(),count);}
  await page.getByRole('searchbox',{name:'Find a typeface'}).fill('JetBrains');assert.equal(await page.locator('.font-option:visible').count(),1);await choose('jetbrains');assert.equal(await page.locator('#rack-font-name').textContent(),'JetBrains Mono');assert((await page.locator('.rack-proof-line').evaluate(el=>getComputedStyle(el).fontFamily)).includes('NW JetBrains Mono'),'Proof follows the selected face live');
  await page.getByRole('searchbox',{name:'Find a typeface'}).fill('nothing-matches');assert(await page.locator('#font-rack-empty').isVisible());assert.equal(await page.locator('#font-rack-empty').textContent(),'No typeface matches ‘nothing-matches’.');await page.getByRole('searchbox',{name:'Find a typeface'}).fill('');
  await choose('fraunces');await page.locator('#panel-content').evaluate(el=>el.scrollTop=0);await page.screenshot({path:path.join(__dirname,'font-rack-412.png')});
  for(const width of [320,412,800,1280]){await page.setViewportSize({width,height:915});assert(await page.locator('#panel-content').evaluate(el=>el.scrollWidth<=el.clientWidth),'Rack fits '+width);assert(await page.locator('.font-rack-grid').evaluate(el=>el.scrollWidth<=el.clientWidth),'Cards fit '+width);}
  await page.setViewportSize({width:320,height:568});await page.locator('#panel-content').evaluate(el=>el.scrollTop=0);await page.screenshot({path:path.join(__dirname,'font-rack-320.png')});await close();
  assert((await page.locator('#markdown').evaluate(el=>getComputedStyle(el).fontFamily)).includes('NW Fraunces'));assert.equal(await page.locator('.type-trigger-name').textContent(),'Fraunces');assert((await page.locator('#markdown h1').evaluate(el=>getComputedStyle(el).fontFamily)).includes('NW Fraunces'),'Page headings must share the selected reading font');assert.equal(await page.locator('#markdown pre code').evaluate(el=>getComputedStyle(el).fontFamily),codeFont);
  await page.locator('.mobile-nav [data-action=terminal]').click();await page.locator('#terminal-words').waitFor();await page.locator('#terminal-seek').evaluate(el=>{el.value=20;el.dispatchEvent(new Event('input',{bubbles:true}));});await page.locator('[data-group="2"]').click();
  const fonts=await page.evaluate(async()=>Object.keys((await import('/reader-fonts.js')).readingFonts));
  await open();
  for(const id of fonts){await choose(id);await page.waitForTimeout(30);const fits=await page.locator('.terminal-word').evaluateAll(els=>els.map(el=>({width:el.getBoundingClientRect().width,slot:el.parentElement.clientWidth,font:parseFloat(getComputedStyle(el).fontSize)})));assert(fits.length===2&&fits.every(fit=>fit.width<=fit.slot+1&&fit.font>=24),id+' fits compact word slots '+JSON.stringify(fits));assert.equal(await page.locator('#terminal-seek').inputValue(),'20');}
  await choose('newsreader');await close();
  for(const style of ['classic','cyberdeck','phosphor','mixtape','orbital','nocturne']){
   await page.setViewportSize({width:412,height:915});await page.locator('#content [data-action=settings]').click();assert.equal(await page.getByRole('tab',{name:'Read',exact:true}).getAttribute('aria-selected'),'true','Preferences opens on Read inside Read');await page.getByRole('tab',{name:'Read',exact:true}).click();await page.locator('#panel-content [data-read-style="'+style+'"]').click();assert.equal(await page.locator('#panel-content [data-read-style="'+style+'"]').getAttribute('aria-pressed'),'true');await page.waitForFunction(style=>document.body.dataset.terminalPresentation===style,style);await close();await open();await choose('lora');await close();
   assert.equal(await page.locator('#terminal-seek').inputValue(),'20');assert.equal(await page.locator('[data-group="2"]').getAttribute('aria-pressed'),'true');assert((await page.locator('#terminal-words').evaluate(el=>getComputedStyle(el).fontFamily)).includes('NW Lora'));
   const trigger=await page.getByRole('button',{name:'Choose reading typeface',exact:true}).boundingBox();assert(trigger.width>=44&&trigger.height>=28);await page.screenshot({path:path.join(__dirname,'font-control-'+style+'.png')});
  }
  await page.locator('#terminal-play').click();await open();assert.equal(await page.locator('#terminal-status').textContent(),'Paused');const paused=await page.locator('#terminal-seek').inputValue();await choose('inter');await close();assert.equal(await page.locator('#terminal-seek').inputValue(),paused);
  await page.locator('#terminal-blackout').click();assert.equal(await page.getByRole('button',{name:'Choose reading typeface',exact:true}).isVisible(),false);await page.keyboard.press('Escape');
  await page.reload();await page.waitForFunction(()=>!!window.Nightwire&&!!document.querySelector('.resume-sheet'));await page.locator('.mobile-nav [data-action=terminal]').click();await page.locator('#terminal-words').waitFor();assert.equal(await page.locator('.type-trigger-name').textContent(),'Inter');assert.equal(await page.locator('#terminal-seek').inputValue(),paused);assert.equal((await page.evaluate(()=>Nightwire.classifierInput())).contentRevision,original.contentRevision);
  assert.deepEqual(errors,[]);assert.deepEqual(external,[]);console.log('Font rack: 20 specimens, category/search/empty states, live Page/Read controls, all fonts fit compact words, all six themes, real font refitting, pause/position/group persistence, reload/blackout, source separation and zero external requests passed.');
 }finally{await browser.close();server.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
