if(process.platform==='android')Object.defineProperty(process,'platform',{value:'linux'});
const fs=require('node:fs'),http=require('node:http'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require('../../folio/node_modules/playwright'),launch=require('../../folio/tests/gpu-launch.cjs');
const root=path.resolve(__dirname,'../assets');
const server=http.createServer((req,res)=>{const file=path.join(root,req.url==='/'?'index.html':decodeURIComponent(req.url.split('?')[0]));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(err,data)=>{if(err){res.writeHead(404).end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.html')?'text/html':file.endsWith('.ttf')?'font/ttf':file.endsWith('.woff2')?'font/woff2':'text/plain');res.end(data);});});
(async()=>{
 await new Promise(r=>server.listen(8799,'127.0.0.1',r));const browser=await chromium.launch({...launch(),headless:true}),page=await browser.newPage({viewport:{width:412,height:915},hasTouch:true});const errors=[],external=[],failures=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:8799/'))external.push(r.url());});
 try{
 await page.goto('http://127.0.0.1:8799/');await page.waitForFunction(()=>!!window.Nightwire);await page.getByRole('button',{name:'Graph',exact:true}).click();await page.getByText('Make a connection.',{exact:true}).waitFor();await page.screenshot({path:path.join(__dirname,'trace-empty-412.png')});
 await page.locator('#file-input').setInputFiles({name:'The-field-notes-source-cartridge-with-a-very-long-filename.md',mimeType:'text/markdown',buffer:Buffer.from('# Field notes\n\n#reading #tools\n\n## First section\n\nSmall observations and [an external reference](https://example.com).\n\n## Second section\n\n### A detail\n\nUseful lines.')});await page.locator('#markdown h1').waitFor();await page.getByRole('button',{name:'Graph of this file'}).click();await page.locator('#graph-canvas canvas').waitFor();await page.waitForTimeout(1300);
 for(const [width,height]of [[320,568],[348,790],[360,640],[393,760],[412,820],[412,915],[768,915],[1280,720],[1280,915],[780,360],[915,412]]){
 await page.setViewportSize({width,height});await page.waitForTimeout(180);const g=await page.evaluate(()=>{const root=document.querySelector('.graph-main'),frame=document.querySelector('.graph-frame'),nav=document.querySelector('.mobile-nav'),rect=frame.getBoundingClientRect();return {scrollX:document.documentElement.scrollWidth>innerWidth,rootBottom:root.getBoundingClientRect().bottom,navTop:getComputedStyle(nav).display==='none'?innerHeight:nav.getBoundingClientRect().top,frameWidth:rect.width,frameHeight:rect.height,controls:[...root.querySelectorAll('button,select')].map(el=>{const r=el.getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return {name:el.getAttribute('aria-label')||el.textContent.trim(),width:r.width,height:r.height,hit:hit===el||el.contains(hit)};})};});if(g.scrollX||g.frameWidth<120||g.frameHeight<90||g.controls.some(c=>c.height<27||c.width<32||(!c.hit&&height>500))||height>500&&g.rootBottom>g.navTop+1)failures.push({width,height,g});await page.screenshot({path:path.join(__dirname,`trace-board-${width}x${height}.png`)});
 }
 await page.setViewportSize({width:412,height:915});await page.getByRole('button',{name:'Tags graph layer'}).click();assert.equal(await page.getByRole('button',{name:'Tags graph layer'}).getAttribute('aria-pressed'),'false');assert.equal(await page.locator('[data-graph-tally=tag]').textContent(),'0');await page.getByRole('button',{name:'All files',exact:true}).click();assert.equal(await page.getByRole('button',{name:'All files',exact:true}).getAttribute('aria-pressed'),'true');
 await page.getByRole('button',{name:'Zoom graph in'}).click();await page.getByRole('button',{name:'Fit graph to screen'}).click();await page.waitForTimeout(1500);
 const dot=await page.locator('#graph-canvas canvas').first().evaluate(canvas=>{const p=canvas.getContext('2d').getImageData(0,0,canvas.width,canvas.height);for(let y=0;y<canvas.height;y++)for(let x=0;x<canvas.width;x++){const i=(y*canvas.width+x)*4;if(p.data[i]===200&&p.data[i+1]===250&&p.data[i+2]===114)return {x:x/(canvas.width/canvas.clientWidth),y:y/(canvas.height/canvas.clientHeight)};}return null;});assert(dot,'visible document node');await page.locator('#graph-canvas canvas').first().click({position:dot});await page.getByRole('button',{name:'Read file',exact:true}).waitFor();await page.screenshot({path:path.join(__dirname,'trace-inspector-412.png')});await page.getByRole('button',{name:'Read file',exact:true}).click();await page.locator('#markdown h1').waitFor();
 await page.getByRole('button',{name:'Graph of this file'}).click();await page.locator('#graph-canvas canvas').waitFor();await page.waitForTimeout(1400);await page.screenshot({path:path.join(__dirname,'trace-heading-check.png')});const heading=await page.locator('#graph-canvas canvas').first().evaluate(canvas=>{const p=canvas.getContext('2d').getImageData(0,0,canvas.width,canvas.height);for(let y=0;y<canvas.height;y++)for(let x=0;x<canvas.width;x++){const i=(y*canvas.width+x)*4;if(p.data[i]===117&&p.data[i+1]===223&&p.data[i+2]===235)return {x:x/(canvas.width/canvas.clientWidth),y:y/(canvas.height/canvas.clientHeight)};}return null;});assert(heading,'visible heading node');await page.locator('#graph-canvas canvas').first().tap({position:heading});await page.locator('#markdown h2').first().waitFor();assert.deepEqual(errors,[]);assert.deepEqual(external,[]);assert.deepEqual(failures,[]);console.log('TRACE graph board: eleven sizes, source/scope/layer controls, real node tallies, zoom/fit, document inspection/open, heading touch navigation, empty state and zero external requests passed.');
 }finally{await browser.close();server.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
