if(process.platform==='android')Object.defineProperty(process,'platform',{value:'linux'});
const fs=require('node:fs'),http=require('node:http'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require('../../folio/node_modules/playwright'),launch=require('../../folio/tests/gpu-launch.cjs');
const root=path.resolve(__dirname,'../assets');
const server=http.createServer((req,res)=>{const file=path.join(root,req.url==='/'?'index.html':decodeURIComponent(req.url.split('?')[0]));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(err,data)=>{if(err){res.writeHead(404).end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.html')?'text/html':file.endsWith('.ttf')?'font/ttf':file.endsWith('.woff2')?'font/woff2':'text/plain');res.end(data);});});
(async()=>{
 await new Promise(r=>server.listen(8793,'127.0.0.1',r));const browser=await chromium.launch({...launch(),headless:true});const page=await browser.newPage({viewport:{width:412,height:915},hasTouch:true});const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error('Browser error:',e.message);});
 const tab=()=>page.locator('.mobile-nav [data-action=terminal]');const position=()=>page.locator('#terminal-seek').inputValue();
 const setRange=async(selector,value)=>page.locator(selector).evaluate((el,value)=>{el.value=value;el.dispatchEvent(new Event('input',{bubbles:true}));},String(value));
 try{
  await page.addInitScript(()=>{if(!localStorage.getItem('settings'))localStorage.setItem('settings',JSON.stringify({terminalStyle:'classic'}));});await page.goto('http://127.0.0.1:8793/');await page.waitForFunction(()=>!!window.Nightwire);await tab().click();await page.locator('.terminal-empty').waitFor();
  const prose='Every small detail makes room for attention. Read slowly, follow the thread, keep what matters.'.split(' ');
  const text='# Deck\n\n'+Array.from({length:90},(_,i)=>prose[i%prose.length]).join(' ')+'\n\n## Close\n\n'+ 'supercalifragilistic'.repeat(12)+' café 日本語\n';
  await page.locator('#file-input').setInputFiles({name:'Deck.md',mimeType:'text/markdown',buffer:Buffer.from(text)});await page.locator('#markdown h1').waitFor();const input=await page.evaluate(()=>Nightwire.classifierInput());await page.locator('[data-action=more]').click();await page.getByRole('button',{name:'Terminal reading',exact:true}).last().click();await page.locator('#terminal-words').waitFor();
  assert.equal(await page.locator('.terminal-word').count(),1);assert.equal(await page.locator('.terminal-word b').textContent(),'De');
  const ruler=await page.locator('#terminal-speed-input').boundingBox();await page.touchscreen.tap(ruler.x+ruler.width*.7,ruler.y+ruler.height/2);assert(Number(await page.locator('#terminal-speed-input').inputValue())>500,'Touching the ruler adjusts WPM');await page.locator('#terminal-slower').click();const beforeStep=Number(await page.locator('#terminal-speed-input').inputValue());await page.locator('#terminal-faster').click();assert.equal(Number(await page.locator('#terminal-speed-input').inputValue()),beforeStep+10);
  await setRange('#terminal-speed-input',1000);await page.locator('#terminal-play').click();await page.waitForFunction(()=>Number(document.querySelector('#terminal-seek').value)>=3,{},{timeout:5000}).catch(async e=>{console.error(await page.locator('.terminal-deck').innerText());throw e;});await page.locator('#terminal-play').click();const paused=await position();await page.waitForTimeout(220);assert.equal(await position(),paused);
  await page.locator('[data-group="2"]').click();assert.equal(await page.locator('.terminal-word').count(),2);await page.locator('#terminal-bionic').click();assert.equal(await page.locator('.terminal-word b').count(),0);
  await page.locator('#terminal-play').click();await page.getByRole('button',{name:'Reading preferences',exact:true}).click();assert.equal(await page.locator('#terminal-status').textContent(),'PAUSED');const dialogPos=await position();await page.waitForTimeout(200);assert.equal(await position(),dialogPos);await page.getByRole('button',{name:'Close panel'}).click();
  await setRange('#terminal-seek',45);await page.locator('.mobile-nav [data-action=home]').click();await tab().click();await page.locator('#terminal-words').waitFor();assert.equal(await position(),'45');assert.equal(await page.locator('#terminal-wpm').textContent(),'1000');assert.equal(await page.locator('[data-group="2"]').getAttribute('aria-pressed'),'true');
  await page.reload();await page.waitForFunction(()=>!!window.Nightwire&&!!document.querySelector('.resume-sheet'));await tab().click();await page.locator('#terminal-words').waitFor();assert.equal(await position(),'45');
  await page.locator('#terminal-play').click();await page.evaluate(()=>Nightwire.pauseReading());const nativePaused=await position();await page.waitForTimeout(200);assert.equal(await position(),nativePaused);await page.locator('#terminal-play').click();await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));delete document.hidden;});const hiddenPaused=await position();await page.waitForTimeout(200);assert.equal(await position(),hiddenPaused);
  await setRange('#terminal-seek',92);for(const width of [320,360,412,768,1280]){await page.setViewportSize({width,height:915});await page.waitForTimeout(120);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No horizontal overflow at '+width);assert(await page.locator('#terminal-words').evaluate(el=>el.scrollWidth<=el.parentElement.clientWidth),'Long word fits');await page.screenshot({path:path.join(__dirname,`terminal-${width}.png`),fullPage:true});}
  await page.setViewportSize({width:412,height:915});await page.locator('#terminal-document').click();await page.locator('#markdown h2').waitFor();assert(await page.locator('#markdown h2').evaluate(el=>el.getBoundingClientRect().top<innerHeight),'Page button returns to current section');assert.equal((await page.evaluate(()=>Nightwire.classifierInput())).contentRevision,input.contentRevision);
  await tab().click();await page.locator('#terminal-words').waitFor();await page.locator('#terminal-play').click();await page.locator('#file-input').setInputFiles({name:'Other.md',mimeType:'text/markdown',buffer:Buffer.from('# Other\n\none two three')});await page.locator('#markdown h1').waitFor();await page.waitForTimeout(150);assert.equal(await page.locator('#markdown h1').textContent(),'Other');await tab().click();await page.locator('#terminal-words').waitFor();assert.equal(await page.locator('.terminal-filename').textContent(),'Other.md');
  await page.locator('#terminal-play').click();await page.locator('#terminal-file').click();assert.equal(await page.locator('#terminal-status').textContent(),'PAUSED','Choosing a file pauses playback');const filePause=await position();await page.waitForTimeout(220);assert.equal(await position(),filePause);assert.equal(await page.locator('select#terminal-file').count(),0,'File picker uses Nightwire UI');await page.screenshot({path:path.join(__dirname,'terminal-chooser.png')});await page.getByRole('button',{name:'Read Deck.md',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.terminal-filename')?.textContent==='Deck.md');assert.equal(await page.locator('#terminal-status').textContent(),'PAUSED');
  await setRange('#terminal-seek',45);await page.locator('#terminal-bionic').click();await page.locator('[data-group="1"]').click();await setRange('#terminal-speed-input',300);await page.waitForTimeout(350);assert.equal(await page.locator('.terminal-filename').textContent(),'Deck.md');await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(80);assert(await page.locator('#terminal-bionic').evaluate(el=>el.getBoundingClientRect().bottom<=document.querySelector('.mobile-nav').getBoundingClientRect().top),'Reading options fit above phone navigation');await page.screenshot({path:path.join(__dirname,'terminal-normal.png'),fullPage:true});
  await page.emulateMedia({reducedMotion:'reduce'});await setRange('#terminal-speed-input',300);assert.equal(await page.locator('#terminal-wpm').evaluate(el=>getComputedStyle(el).transform),'none');
  await page.locator('#file-input').setInputFiles({name:'Code-only.md',mimeType:'text/markdown',buffer:Buffer.from('```js\nconst x = 1;\n```')});await page.locator('#markdown pre').waitFor();await tab().click();await page.locator('.terminal-no-prose').waitFor();assert(await page.locator('.terminal-empty-help').isVisible(),'Empty prose explanation stays visible on phones');assert(await page.locator('#terminal-play').isDisabled());
  assert.deepEqual(errors,[]);console.log('Terminal reader: playback, controls, progress, lifecycle, hot-open, section return, responsive long words and reduced motion passed');
 }finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
